import pytest
from pydantic import ValidationError
from hypothesis import given, strategies as st, settings, HealthCheck
import re

from app.schemas.user import UserCreate

# --- Standard Pytest Validation Tests ---

def test_user_create_success():
    """Tests successful creation of a UserCreate instance with valid data."""
    user_data = {
        "username": "validuser",
        "email": "VALID.USER@example.com",
        "password": "ValidPassword123!"
    }
    user = UserCreate(**user_data)
    assert user.username == "validuser"
    assert user.email == "valid.user@example.com" # Should be lowercased
    assert user.password == "ValidPassword123!"

@pytest.mark.parametrize("invalid_email", [
    "plainaddress",
    "#@%^%#$@#$@#.com",
    "@example.com",
    "email.example.com",
    "email@example@example.com",
    ".email@example.com",
    "email.@example.com",
    "email..email@example.com",
    "email@example.com (Joe Smith)",
    "email@example",
    "email@-example.com",
    "email@111.222.333.44444",
    "email@example..com",
    "Abc..123@example.com",
])
def test_user_create_invalid_email(invalid_email):
    """Tests that UserCreate raises a ValidationError for malformed emails."""
    with pytest.raises(ValidationError):
        UserCreate(username="testuser", email=invalid_email, password="ValidPassword123!")

def test_user_create_invalid_password_too_short():
    """Tests that UserCreate raises a ValidationError for a password that is too short."""
    with pytest.raises(ValidationError, match="Password must be at least 8 characters long"):
        UserCreate(username="testuser", email="test@example.com", password="short")


@pytest.mark.parametrize("invalid_password, reason", [
    ("nouppercase1!", "no uppercase"),
    ("NOLOWERCASE1!", "no lowercase"),
    ("NoDigits!!", "no digits"),
    ("NoSpecial123", "no special char"),
])
def test_user_create_invalid_password_missing_chars(invalid_password, reason):
    """Tests that UserCreate raises a ValidationError for passwords missing required characters."""
    with pytest.raises(ValidationError, match="Password must contain at least one"):
        UserCreate(username="testuser", email="test@example.com", password=invalid_password)


@pytest.mark.parametrize("invalid_username, reason", [
    ("sh", "too short"),
    ("a_very_long_username_that_is_invalid", "too long"),
    ("invalid-char", "not alphanumeric"),
    ("invalid space", "not alphanumeric"),
])
def test_user_create_invalid_username(invalid_username, reason):
    """Tests that UserCreate raises a ValidationError for invalid usernames."""
    with pytest.raises(ValidationError, match="Username must be"):
        UserCreate(username=invalid_username, email="test@example.com", password="ValidPassword123!")

# --- Property-Based Tests with Hypothesis ---

# Strategy for generating valid passwords
valid_password_st = st.from_regex(
    r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*(),.?\":{}|<>])[A-Za-z\d!@#$%^&*(),.?\":{}|<>]{8,72}$",
    fullmatch=True
)

# Strategy for generating valid usernames
valid_username_st = st.from_regex(r"^[a-zA-Z0-9]{3,20}$", fullmatch=True)

@settings(max_examples=50, suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much])
@given(
    username=valid_username_st,
    email=st.emails(),
    password=valid_password_st
)
def test_user_create_hypothesis_valid_data(username, email, password):
    """
    Tests that any combination of valid data generated by Hypothesis
    successfully creates a UserCreate instance.
    """
    user = UserCreate(username=username, email=email, password=password)
    assert user.username == username
    assert user.password == password
    # We don't assert email equality directly, as Pydantic performs
    # normalization (e.g., for international domains) which is the correct behavior.
    assert user.email is not None
