"""add user rpg stats

Revision ID: 0160894f89ad
Revises: f0780cb1ca9d
Create Date: 2026-01-10 19:52:15.034795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0160894f89ad'
down_revision: Union[str, Sequence[str], None] = 'f0780cb1ca9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_onboarding_completed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user', sa.Column('daily_reached_goal', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('user', sa.Column('stat_strength', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('user', sa.Column('stat_endurance', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('user', sa.Column('stat_intelligence', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('user', sa.Column('stat_focus', sa.Integer(), nullable=False, server_default=sa.text('10')))
    
    # Remove server_default after the columns are created if you don't want it to persist for future inserts (optional but cleaner)
    # op.alter_column('user', 'is_onboarding_completed', server_default=None)
    # ... (omitted for brevity, keeping default is fine/safer)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stat_focus')
    op.drop_column('user', 'stat_intelligence')
    op.drop_column('user', 'stat_endurance')
    op.drop_column('user', 'stat_strength')
    op.drop_column('user', 'daily_reached_goal')
    op.drop_column('user', 'is_onboarding_completed')
    # ### end Alembic commands ###
