"""refactor_domain_models

Revision ID: 29b91b1312eb
Revises: 692cf3d14e53
Create Date: 2026-02-07 23:05:53.699910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29b91b1312eb'
down_revision: Union[str, Sequence[str], None] = '692cf3d14e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop existing enum type 'dimension' to avoid conflict with table name 'dimension'
    op.execute("DROP TYPE IF EXISTS dimension CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimension_name'), 'dimension', ['name'], unique=True)
    
    # --- SEED DATA ---
    import uuid
    dimensions_data = [
        {"id": str(uuid.uuid4()), "name": "Energia", "description": "Energy - Il tempio fisico"},
        {"id": str(uuid.uuid4()), "name": "Chiarezza", "description": "Clarity - La mente focalizzata"},
        {"id": str(uuid.uuid4()), "name": "Relazioni", "description": "Relationships - La tribù e il cuore"},
        {"id": str(uuid.uuid4()), "name": "Anima", "description": "Soul - Il perché profondo"},
    ]
    for dim in dimensions_data:
        op.execute(
            sa.text(f"INSERT INTO dimension (id, name, description) VALUES ('{dim['id']}', '{dim['name']}', '{dim['description']}')")
        )

    op.create_table('action',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fulfillment_score', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('dimension_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimension.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_dimension_id'), 'action', ['dimension_id'], unique=False)
    op.create_index(op.f('ix_action_start_time'), 'action', ['start_time'], unique=False)
    op.create_index(op.f('ix_action_user_id'), 'action', ['user_id'], unique=False)
    op.drop_index(op.f('ix_activitylog_category_id'), table_name='activitylog', if_exists=True)
    op.drop_index(op.f('ix_activitylog_start_time'), table_name='activitylog', if_exists=True)
    op.drop_index(op.f('ix_activitylog_user_id'), table_name='activitylog', if_exists=True)
    op.execute("DROP TABLE IF EXISTS activitylog CASCADE")
    op.drop_index(op.f('ix_category_dimension'), table_name='category', if_exists=True)
    op.drop_index(op.f('ix_category_user_id'), table_name='category', if_exists=True)
    op.execute("DROP TABLE IF EXISTS category CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dimension', postgresql.ENUM('body', 'mind', 'emotions', 'spirit', name='dimension'), server_default=sa.text("'mind'::dimension"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='category_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='category_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_category_user_id'), 'category', ['user_id'], unique=False)
    op.create_index(op.f('ix_category_dimension'), 'category', ['dimension'], unique=False)
    op.create_table('activitylog',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('activitylog_category_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('activitylog_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('activitylog_pkey'))
    )
    op.create_index(op.f('ix_activitylog_user_id'), 'activitylog', ['user_id'], unique=False)
    op.create_index(op.f('ix_activitylog_start_time'), 'activitylog', ['start_time'], unique=False)
    op.create_index(op.f('ix_activitylog_category_id'), 'activitylog', ['category_id'], unique=False)
    op.drop_index(op.f('ix_action_user_id'), table_name='action')
    op.drop_index(op.f('ix_action_start_time'), table_name='action')
    op.drop_index(op.f('ix_action_dimension_id'), table_name='action')
    op.drop_table('action')
    op.drop_index(op.f('ix_dimension_name'), table_name='dimension')
    op.drop_table('dimension')
    # ### end Alembic commands ###
