"""add_rank_score_to_user

Revision ID: 3ddb370b0a94
Revises: 9e3b26d6d248
Create Date: 2026-02-21 23:13:50.561327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ddb370b0a94'
down_revision: Union[str, Sequence[str], None] = '9e3b26d6d248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rank_score', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rank_score')
    # ### end Alembic commands ###
