"""add_dimension_to_category

Revision ID: 692cf3d14e53
Revises: 7289b634a242
Create Date: 2026-02-07 22:34:06.803753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '692cf3d14e53'
down_revision: Union[str, Sequence[str], None] = '7289b634a242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type
    sa.Enum('body', 'mind', 'emotions', 'spirit', name='dimension').create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('dimension', sa.Enum('body', 'mind', 'emotions', 'spirit', name='dimension'), nullable=False, server_default='mind'))
    op.create_index(op.f('ix_category_dimension'), 'category', ['dimension'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_dimension'), table_name='category')
    op.drop_column('category', 'dimension')
    # ### end Alembic commands ###
    
    # Drop the enum type
    sa.Enum(name='dimension').drop(op.get_bind(), checkfirst=True)
