"""remove_rpg_logic_and_onboarding

Revision ID: 7289b634a242
Revises: 0160894f89ad
Create Date: 2026-02-07 17:33:25.293151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7289b634a242'
down_revision: Union[str, Sequence[str], None] = '0160894f89ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stat_intelligence')
    op.drop_column('user', 'daily_reached_goal')
    op.drop_column('user', 'stat_focus')
    op.drop_column('user', 'stat_strength')
    op.drop_column('user', 'is_onboarding_completed')
    op.drop_column('user', 'stat_endurance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stat_endurance', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_onboarding_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('stat_strength', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('stat_focus', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('daily_reached_goal', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('stat_intelligence', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
